name: Coveralls

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
