name: Coveralls

on: ["push"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install mocha-lcov-reporter
        run: npm install --save-dev mocha-lcov-reporter

      - name: Run tests
        run: npm test -- --reporter mocha-lcov-reporter || true

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.4
        with:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN}}
